changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.spec.{ts,tsx}"

nodeLinker: node-modules

# httpProxy: http://proxybmg.bancobmg.com.br:8080/

# httpsProxy: http://proxybmg.bancobmg.com.br:8080/

# npmRegistryServer: "http://nexus-prd/repository/npm-public/"

# unsafeHttpWhitelist: ["proxybmg.bancobmg.com.br", "nexus-prd"]

yarnPath: .yarn/releases/yarn-4.0.2.cjs
